### ISSUE TITLE
Create and test design of main page

### ISSUE THREAD

**Issue by Miki-san** [IVBO-07-19/scholarship-frontend#5]
Разработать дизайн и расположение функциональных блоков системы, расположить их на основной странице, проверить работу на различных типах устройств: Смартфон, Ноутбук, ПК.

**Comment by TheHarald** [comment]
Создан предварительный дизайн [Сайта](https://clck.ru/Ti3E8)

**Comment by katyagibova** [comment]
Готова первичная разметка. Пока все ок)0
